/**
 * Mock data for dashboards in demo mode
 */

export const mockSupplies = [
  // Legal Sea Foods
  {
    id: 'supply-1',
    restaurant_id: 'prof-rest-1',
    shell_type: 'lobster',
    weekly_quantity_kg: 45,
    storage_method: 'frozen',
    cleanliness_level: 'clean',
    pickup_window: 'Mon-Fri 10am-2pm',
    notes: 'Large volume available year-round',
    status: 'active',
    created_at: '2024-01-15',
    restaurant: {
      id: 'prof-rest-1',
      restaurant_name: 'Legal Sea Foods - Seaport',
      address: '270 Northern Ave, Boston, MA 02210',
      latitude: 42.3467,
      longitude: -71.0448,
      storage_method: 'frozen',
      cleanliness_level: 'clean',
      contact_phone: '(617) 477-2900',
    },
  },
  {
    id: 'supply-2',
    restaurant_id: 'prof-rest-1',
    shell_type: 'shrimp',
    weekly_quantity_kg: 30,
    storage_method: 'frozen',
    cleanliness_level: 'clean',
    pickup_window: 'Mon-Fri 10am-2pm',
    notes: 'Pre-rinsed and ready for extraction',
    status: 'active',
    created_at: '2024-01-15',
    restaurant: {
      id: 'prof-rest-1',
      restaurant_name: 'Legal Sea Foods - Seaport',
      address: '270 Northern Ave, Boston, MA 02210',
      latitude: 42.3467,
      longitude: -71.0448,
      storage_method: 'frozen',
      cleanliness_level: 'clean',
      contact_phone: '(617) 477-2900',
    },
  },
  // Neptune Oyster
  {
    id: 'supply-3',
    restaurant_id: 'prof-rest-2',
    shell_type: 'lobster',
    weekly_quantity_kg: 25,
    storage_method: 'refrigerated',
    cleanliness_level: 'clean',
    pickup_window: 'Tue-Thu 3pm-5pm',
    notes: 'Fresh shells from daily service',
    status: 'active',
    created_at: '2024-01-16',
    restaurant: {
      id: 'prof-rest-2',
      restaurant_name: 'Neptune Oyster',
      address: '63 Salem St, Boston, MA 02113',
      latitude: 42.3647,
      longitude: -71.0542,
      storage_method: 'refrigerated',
      cleanliness_level: 'clean',
      contact_phone: '(617) 742-3474',
    },
  },
  {
    id: 'supply-4',
    restaurant_id: 'prof-rest-2',
    shell_type: 'crab',
    weekly_quantity_kg: 15,
    storage_method: 'refrigerated',
    cleanliness_level: 'clean',
    pickup_window: 'Tue-Thu 3pm-5pm',
    notes: 'Dungeness and king crab mix',
    status: 'active',
    created_at: '2024-01-16',
    restaurant: {
      id: 'prof-rest-2',
      restaurant_name: 'Neptune Oyster',
      address: '63 Salem St, Boston, MA 02113',
      latitude: 42.3647,
      longitude: -71.0542,
      storage_method: 'refrigerated',
      cleanliness_level: 'clean',
      contact_phone: '(617) 742-3474',
    },
  },
];

export const mockDemands = [
  // MIT
  {
    id: 'demand-1',
    lab_id: 'prof-lab-1',
    shell_type_needed: 'shrimp',
    weekly_quantity_needed_kg: 25,
    extraction_frequency: 'weekly',
    max_pickup_radius_km: 15,
    application: 'Chitosan extraction for biodegradable medical implants',
    priority_level: 'high',
    status: 'active',
    created_at: '2024-01-10',
    lab: {
      id: 'prof-lab-1',
      institution_name: 'Massachusetts Institute of Technology',
      dept: 'Materials Science',
      lab_name: 'Biomaterials Research Lab',
      address: '77 Massachusetts Ave, Cambridge, MA 02139',
      latitude: 42.3601,
      longitude: -71.0942,
      extraction_frequency: 'weekly',
      max_pickup_radius_km: 15,
      application: 'Chitosan extraction for biodegradable medical implants',
      contact_phone: '(617) 253-1000',
    },
  },
  {
    id: 'demand-2',
    lab_id: 'prof-lab-1',
    shell_type_needed: 'crab',
    weekly_quantity_needed_kg: 18,
    extraction_frequency: 'weekly',
    max_pickup_radius_km: 15,
    application: 'Testing different chitosan compositions for medical device coatings',
    priority_level: 'medium',
    status: 'active',
    created_at: '2024-01-10',
    lab: {
      id: 'prof-lab-1',
      institution_name: 'Massachusetts Institute of Technology',
      dept: 'Materials Science',
      lab_name: 'Biomaterials Research Lab',
      address: '77 Massachusetts Ave, Cambridge, MA 02139',
      latitude: 42.3601,
      longitude: -71.0942,
      extraction_frequency: 'weekly',
      max_pickup_radius_km: 15,
      application: 'Chitosan extraction for biodegradable medical implants',
      contact_phone: '(617) 253-1000',
    },
  },
  // Harvard
  {
    id: 'demand-3',
    lab_id: 'prof-lab-2',
    shell_type_needed: 'lobster',
    weekly_quantity_needed_kg: 30,
    extraction_frequency: 'biweekly',
    max_pickup_radius_km: 20,
    application: 'Development of eco-friendly packaging materials',
    priority_level: 'medium',
    status: 'active',
    created_at: '2024-01-12',
    lab: {
      id: 'prof-lab-2',
      institution_name: 'Harvard University',
      dept: 'Engineering',
      lab_name: 'Sustainable Polymers Lab',
      address: '29 Oxford St, Cambridge, MA 02138',
      latitude: 42.3770,
      longitude: -71.1167,
      extraction_frequency: 'biweekly',
      max_pickup_radius_km: 20,
      application: 'Development of eco-friendly packaging materials',
      contact_phone: '(617) 495-1000',
    },
  },
];

export const mockMatches = [
  {
    id: 'match-1',
    supply_id: 'supply-2',
    demand_id: 'demand-1',
    restaurant_id: 'prof-rest-1',
    lab_id: 'prof-lab-1',
    shell_type: 'shrimp',
    matched_quantity_kg: 25,
    distance_km: 3.2,
    status: 'active',
    created_at: '2024-01-20',
    restaurant: {
      id: 'prof-rest-1',
      restaurant_name: 'Legal Sea Foods - Seaport',
      address: '270 Northern Ave, Boston, MA 02210',
      latitude: 42.3467,
      longitude: -71.0448,
    },
    lab: {
      id: 'prof-lab-1',
      institution_name: 'Massachusetts Institute of Technology',
      lab_name: 'Biomaterials Research Lab',
      address: '77 Massachusetts Ave, Cambridge, MA 02139',
      latitude: 42.3601,
      longitude: -71.0942,
    },
    supply: {
      shell_type: 'shrimp',
      weekly_quantity_kg: 30,
    },
    demand: {
      shell_type_needed: 'shrimp',
      weekly_quantity_needed_kg: 25,
    },
  },
  {
    id: 'match-2',
    supply_id: 'supply-3',
    demand_id: 'demand-3',
    restaurant_id: 'prof-rest-2',
    lab_id: 'prof-lab-2',
    shell_type: 'lobster',
    matched_quantity_kg: 25,
    distance_km: 2.8,
    status: 'active',
    created_at: '2024-01-21',
    restaurant: {
      id: 'prof-rest-2',
      restaurant_name: 'Neptune Oyster',
      address: '63 Salem St, Boston, MA 02113',
      latitude: 42.3647,
      longitude: -71.0542,
    },
    lab: {
      id: 'prof-lab-2',
      institution_name: 'Harvard University',
      lab_name: 'Sustainable Polymers Lab',
      address: '29 Oxford St, Cambridge, MA 02138',
      latitude: 42.3770,
      longitude: -71.1167,
    },
    supply: {
      shell_type: 'lobster',
      weekly_quantity_kg: 25,
    },
    demand: {
      shell_type_needed: 'lobster',
      weekly_quantity_needed_kg: 30,
    },
  },
];
